app/cliente/views.py
from http import HTTPStatus
from flask import Blueprint, request, session
from flask_cors import CORS
from app.cliente.models import crear_cliente, get_clientes, eliminar_cliente, modificar_cliente, obtener_cliente
import copy

RESPONSE_BODY_DEFAULT = {"message": "", "data": [], "errors": []}
cliente = Blueprint("cliente", __name__, url_prefix="/cliente")

@cliente.route("/", methods=["GET"])
def index():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    clientes = get_clientes()
    response_body["message"] = "Clientes consultados correctamente"
    response_body["data"] = clientes
    return response_body, status_code

@cliente.route("/obtenerUsuario", methods = ["POST"])
def consultar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    cli_v_usuario = request.json["usuario"]
    cli_v_contrasena = request.json["contrasena"]
    if cli_v_usuario != "" and cli_v_usuario != None :
        if cli_v_contrasena != "" and cli_v_contrasena != None :
            cliente = obtener_cliente(cli_v_usuario, cli_v_contrasena)
            if cliente != None:
                response_body["message"] = "Credenciales correctas!"
                response_body["data"] = cliente
                session["username"] = cli_v_usuario
            else:
                response_body["errors"].append("Credenciales incorrectas")
                status_code = HTTPStatus.BAD_REQUEST
        else:
            response_body["errors"].append("Contraseña vacía")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["errors"].append("Usuario vacío")
        status_code = HTTPStatus.BAD_REQUEST
    return response_body, status_code


@cliente.route("/crear", methods=["POST"])
def crear():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    cli_v_usuario = request.json["usuario"]
    cli_v_contrasena = request.json["contrasena"]
    r_contrasena = request.json["r_contrasena"]

    if cli_v_usuario != "" and cli_v_usuario != None :
        if cli_v_contrasena != "" and cli_v_contrasena != None :
            if r_contrasena != cli_v_contrasena :
                response_body["errors"].append("Las contraseñas no coinciden")
                status_code = HTTPStatus.BAD_REQUEST
        
            cliente = crear_cliente(cli_v_usuario, cli_v_contrasena)
            if cliente != None:
                response_body["message"] = "Cliente creado correctamente!"
                response_body["data"] = cliente
                session["username"] = cli_v_usuario

            else:
                response_body["errors"].append("Usuario repetido")
                status_code = HTTPStatus.BAD_REQUEST
        else:
            response_body["errors"].append("Contraseña vacía")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["errors"].append("Usuario vacío")
        status_code = HTTPStatus.BAD_REQUEST

    return response_body, status_code

@cliente.route("/modificar", methods=["PUT"])
def modificar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK

    cli_v_usuario = request.json["cli_v_usuario"]
    cli_v_contrasena = request.json["cli_v_contrasena"]
    cli_i_puntaje = request.json["cli_i_puntaje"]

    if cli_v_usuario != "" and cli_v_usuario != None: 
        if  cli_v_contrasena != "" and cli_v_contrasena != None: 
            if cli_i_puntaje != "" and cli_i_puntaje != None: 
                cliente_mod = modificar_cliente(cli_v_usuario, cli_v_contrasena, cli_i_puntaje)
                if cliente_mod != None:
                    response_body["message"] = "Cliente modificado correctamente!"
                    response_body["data"] = cliente_mod
                else:
                    response_body["message"] = "No se encontro el cliente"
                    response_body["errors"].append("No se encontro el cliente")
                    status_code = HTTPStatus.BAD_REQUEST
            else:
                response_body["message"] = "Debe ingresar un puntaje"
                response_body["errors"].append("Debe ingresar un puntaje")
                status_code = HTTPStatus.BAD_REQUEST
        else:
            response_body["message"] = "Debe ingresar una contraseña"
            response_body["errors"].append("Debe ingresar una contraseña")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["message"] = "Debe ingresar un usuario"
        response_body["errors"].append("Debe ingresar un usuario")
        status_code = HTTPStatus.BAD_REQUEST

    return response_body, status_code

@cliente.route("/eliminar", methods=["DELETE"])
def eliminar():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK
    
    cli_v_usuario = request.json["cli_v_usuario"]

    if cli_v_usuario != None and cli_v_usuario != "":
        if eliminar_cliente(cli_v_usuario):
            response_body["message"] = "Cliente eliminado correctamente!"
        else:
            response_body["message"] = "Error no se encuentra el cliente"
            response_body["errors"].append("Error no se encuentra el cliente")
            status_code = HTTPStatus.BAD_REQUEST
    else:
        response_body["message"] = "Debe ingresar un usuario"
        response_body["errors"].append("Debe ingresar un usuario")
        status_code = HTTPStatus.BAD_REQUEST

    return response_body, status_code

app/juego/views.py
from http import HTTPStatus
from flask import Blueprint, request, render_template, session, redirect, url_for
from app.cliente.models import ranking,agregar_puntaje, mis_puntajes
import copy
RESPONSE_BODY_DEFAULT = {"message": "", "data": [], "errors": []}

juego = Blueprint("juego", __name__, url_prefix="/")


@juego.route("/", methods=["GET"])
def index():
    ranking_p = ranking()
    return render_template('welcome.html', ranking=ranking_p)



@juego.route("/menu", methods=["GET"])
def menu():
    return render_template('menu.html')

@juego.route("/maximos-puntajes", methods=["GET"])
def maximos_puntajes():

    puntajes = mis_puntajes(session['username'])



    return render_template('maximosPuntajes.html', puntajes=puntajes)



@juego.route("/jugar", methods=["GET"])
def jugar():
    return render_template('game.html')


@juego.route("/agregar_puntajes", methods=["POST"])
def agregar_puntajes():
    response_body = copy.deepcopy(RESPONSE_BODY_DEFAULT)
    status_code = HTTPStatus.OK


    puntaje = agregar_puntaje(request.json["puntaje"], session['username'])

    response_body["message"] = "Puntaje actualizado correctamente"
    response_body["data"] = puntaje

    return response_body, status_code




@juego.route("/salir", methods=["GET"])
def salir():
    session.pop('username', None)
    return redirect(url_for('juego.index'))

app/templates/game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}"/>
    <title>Jugar</title>
</head>
<body>

    <section class="container-game">
        <nav class="navbar">
            <a href="{{url_for('juego.menu')}}" class="volver">Volver</a>
            <h1>Froggy road</h1>
        </nav>
        <main class="juego">
        <canvas id="main" width="700" height="750">
            <img id="img_arbol" src="{{ url_for('static', filename='imgs/arbol.png')}}" width="100" height="100">
            <img id="img_camion" src="{{ url_for('static', filename='imgs/camion.png')}}" width="200" height="100">
            <img id="img_carretera" src="{{ url_for('static', filename='imgs/carretera.png')}}" width="100" height="100">
            <img id="img_carro1" src="{{ url_for('static', filename='imgs/carro1.png')}}" width="100" height="100">
            <img id="img_carro2" src="{{ url_for('static', filename='imgs/carro2.png')}}" width="100" height="100">
            <img id="img_carro3" src="{{ url_for('static', filename='imgs/carro3.png')}}" width="100" height="100">
            <img id="img_carro4" src="{{ url_for('static', filename='imgs/carro4.png')}}" width="100" height="100">
            <img id="img_pasto" src="{{ url_for('static', filename='imgs/libre.png')}}" width="100" height="100">
            <img id="img_rana_duerme" src="{{ url_for('static', filename='imgs/rana_duerme.png')}}" width="100" height="100">
            <img id="img_piedra" src="{{ url_for('static', filename='imgs/piedra.png')}}" width="100" height="100">
            <img id="img_puente" src="{{ url_for('static', filename='imgs/puente.png')}}" width="100" height="100">
            <img id="img_rios" src="{{ url_for('static', filename='imgs/rios.png')}}" width="100" height="100">
            <img id="img_salida" src="{{ url_for('static', filename='imgs/salida.png')}}" width="100" height="100">
            <img id="img_jugador1" src="{{ url_for('static', filename='imgs/rana1.png')}}" width="100" height="100">
            <img id="img_jugador2" src="{{ url_for('static', filename='imgs/rana2.png')}}" width="100" height="100">
            <img id="img_jugador3" src="{{ url_for('static', filename='imgs/rana3.png')}}" width="100" height="100">
            <img id="img_jugador4" src="{{ url_for('static', filename='imgs/rana4.png')}}" width="100" height="100">
            <img id="img_bici1" src="{{ url_for('static', filename='imgs/bici1.png')}}" width="100" height="100">
            <img id="img_bici2" src="{{ url_for('static', filename='imgs/bici2.png')}}" width="100" height="100">
            <img id="img_bici3" src="{{ url_for('static', filename='imgs/bici3.png')}}" width="100" height="100">
            <img id="img_vidas" src="{{ url_for('static', filename='imgs/corazon.png')}}" width="42" height="42">
            <img id="img_reloj" src="{{ url_for('static', filename='imgs/reloj.png')}}" width="30" height="45">
            <img id="img_pop" src="{{ url_for('static', filename='imgs/pop.png')}}" width="600" height="331">
            <img id="img_pop_final" src="{{ url_for('static', filename='imgs/pop_final.png')}}" width="285" height="80">
        </canvas>
    </main>
    </section>

    <script src="{{ url_for('static', filename='js/main.js')}}"></script>
</body>
</html>

app/templates/maximosPuntajes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}"/>
    <title>Mis puntajes</title>
</head>
<body>
    <section class="container-game">
        <nav class="navbar">
            <a href="{{url_for('juego.menu')}}" class="volver">Volver</a>
            <h1>Froggy road</h1>
        </nav>
        <div class="main_ranking_container">
            <h2>Mis Maximos Puntajes</h2>
            <div class="main_filaRanking primero">
                <div class="main_puntaje full">
                    <h4>Puntajes</h4>
                </div>
            </div>
             <div class="main_rankings">
                 {% for puntaje in puntajes %}
                    <div class="main_filaRanking">
                        <div class="main_puntaje full">
                            <p>{{puntaje.pun_i_puntaje}}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
</body>
</html>

app/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}"/>
    <title>Menu</title>
</head>
<body>
    <section class="main-menu">
        <h1>Froggy road</h1>
        <div class="content_menu">
            <a class="btns" href="{{url_for('juego.jugar')}}">Jugar</a>
            <a class="btns" id="btnInstrucciones">Instrucciones</a>
            <a class="btns"  href="{{url_for('juego.maximos_puntajes')}}">Maximos puntajes</a>
            <a class="btns" href="{{url_for('juego.salir')}}">Salir</a>
        </div>
    </section>
    <div class="popup" id="instrucciones">
        <div class="content-popup">
            <h3>Instrucciones</h3>
            <div class="instrucciones">
                <img src="{{ url_for('static', filename='img/arrows.png')}}" />
                <p class="instrucciones-text">
                    ¡Se han olvidado de froggy!, intenta cruzar el camino para llegar con tu familia<br>
                    Muevete con las fechas de dirección e intenta esquivar todos los obstaculos
                </p>
            </div>


            <button class="cerrar_pop">Cerrar</button>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/menu.js')}}"></script>
</body>
</html>

app/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}"/>
    <title>Bienvenido</title>
</head>
<body>
    <main class="main">
        <section class="main_forms">
            <h1>Froggy road</h1>
            <div class="main_login">
                <h3>Inicia sesion
                </h3>
                <form class="main_form-login" id="formLogin" method="post" action="{{ url_for('cliente.consultar') }}">
                    <label for="user">Usuario:</label>
                    <input type="text" name="usuario" placeholder="Introduce tu usuario">
                    <label for="password">Contraseña:</label>
                    <input type="password" name="contrasena" placeholder="Introduce la contraseña">
                    <input type="submit" value="Ingresar">
                    <button id="register" class="btns" value="main_register">Registrarse</button>
                </form>
            </div>
            <div class="main_register null">
                <h3>Registrate</h3>
                <form class="main_form-register" id="formRegistro" method="post" action="{{ url_for('cliente.crear') }}">
                    <label for="user">Usuario:</label>
                    <input type="text" name="usuario" placeholder="Introduce tu usuario">
                    <label for="password">Contraseña:</label>
                    <input type="password" name="contrasena" placeholder="Introduce la contraseña">
                    <label for="password">Repita la contraseña:</label>
                    <input type="password" name="r_contrasena" placeholder="Repita la contraseña">


                    <input type="submit" value="Registrarse">
                    <button id="login" class="btns" value="main_login">Volver</button>
                </form>
            </div>
        </section>
        <section class="main_ranking_section">
            <div class="main_ranking_container">
                <h2>Rankings:</h2>
                <div class="main_filaRanking primero">
                    <div class="main_nameRanking">
                        <h4>Nombres</h4>            
                    </div>
                    <div class="main_puntaje">
                        <h4>Puntajes</h4>
                    </div>
                </div>
                <div class="main_rankings">
                    {% for client in ranking %}
                    <div class="main_filaRanking">
                        <div class="main_nameRanking">
                            <p>{{client.cli_v_usuario}}</p>
                        </div>
                        <div class="main_puntaje">
                            <p>{{client.cli_i_puntaje}}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                
            </div>
        </section>
    </main>
    <div class="popup" id="errors">
        <div class="content-popup">
          <h3>Errores</h3>
          <ul id="listErrors">
          </ul>
          <button class="cerrar_pop">Cerrar</button>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/welcome.js')}}"></script>
</body>
</html>